compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: NO
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
